name: Nicholas Reich
title: "Nicholas Reich: Biostatistics and Infectious Disease Epidemiology"

url: "reichlab.github.io"
baseurl: "/"

paginate: 5
paginate_path: "/page:num"
excerpt_separator: <!--more-->

markdown: kramdown

